spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5433/test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        id:
          uuid_generator_strategy: org.hibernate.id.uuid.StandardRandomStrategy
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:
           name: pfe_testing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/pfe


  mail:
    host: smtp.gmail.com
    port: 587
    username: abderrahmenbennacer622@gmail.com
    password: lyaybzextiealols
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


keycloak:
  auth-server-url: http://localhost:9090
  realm: pfe
  resource: pfe-backend-client
  credentials:
    secret: ZxPYUmr6zEEDGGCinjz1Hinpqi6GoNid

  use-resource-role-mappings: true
server:
  port: 8090