spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://localhost:5433/test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
           name: pfe_testing
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pfe
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    from: your-email@gmail.com

keycloak:
  auth-server-url: http://localhost:8080
  realm: pfe
  client-id: admin-cli
  client-secret: your-client-secret
  username: admin
  password: admin
  grant-type: password

server:
  port: 8090