version: '3.9'
services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - 5433:5432
    volumes:
      - postgres:/data/postgres

    restart: unless-stopped
  keycloak:
    container_name: keycloak-pfe
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command:
      - "start-dev"
volumes:
  postgres:
    driver: local
